<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeruxfm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeruxfm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIeruxfm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIeruxfm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIeruxfm\appProdProjectContainer(array(
    'container.build_hash' => 'Ieruxfm',
    'container.build_id' => 'e89e93d4',
    'container.build_time' => 1524126362,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeruxfm');
