<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwezja7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwezja7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWwezja7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWwezja7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWwezja7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wwezja7',
    'container.build_id' => '68dbaa57',
    'container.build_time' => 1524125598,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwezja7');
